Manage_delegation_task:
  description: >
    你是一名任务指派协调员。请根据任务内容 {query}，在已有专家中选出最适合处理该任务的 agent，并进行精准指派。指派时请综合考虑任务主题与各专家的专业背景，确保匹配度最高。
  expected_output: >
    返回被指派执行该任务的专家 agent 名称，确保其最符合任务要求。

AI_export_answer_task:
  description: >
    运用你在该领域的专业知识，对以下问题提供全面的回答：{query}。
    在作答时，重点融入你所在专业领域的洞察与方法，以提升回答的深度和价值。
  expected_output: >
    一份简洁、逻辑清晰、具有专业水准的回答，不超过500字，充分体现你专业领域的特点与理解。
  agent: AI_export

Microbiology_export_answer_task:
  description: >
    运用你在该领域的专业知识，对以下问题提供全面的回答：{query}。
    在作答时，重点融入你所在专业领域的洞察与方法，以提升回答的深度和价值。
  expected_output: >
    一份简洁、逻辑清晰、具有专业水准的回答，不超过500字，充分体现你专业领域的特点与理解。
  agent: Microbiology_export

Integrative_researcher_summary_answer_task:
  description: >
    综合来自不同领域专家的回答，生成一份整合的总结报告，反映其多元观点与洞察。
    你的角色是总结助理，编写内容时不添加新的解释，仅整理专家输入内容。
  expected_output: >
    一份全面且连贯的总结报告，以结构化且中立的方式呈现多个专家的核心观点，突出共识与分歧。
    报告应具备执行摘要风格，篇幅不超过800字。
  agent: Integrative_researcher
  context:
  - AI_export_answer_task
  - Microbiology_export_answer_task

AI_export_reanswer_task:
  description: >
    运用你在人工智能领域的深厚专业知识，对以下问题给出全面且有理有据的回答：{query}。
    与其简单地对比不同领域的方法或表面融合观点，不如以更深层次的一体化思路展开作答。
    请将AI的核心洞察与跨学科专家讨论中提炼出的相关知识无缝整合，用以揭示新的解释视角、解决不确定性，或增强阐述的深度。
  expected_output: >
    一份简洁、逻辑严谨、专业性强的回答（最好不超过500字），既体现出AI领域的专家水准，
    又巧妙融合其他领域的上下文洞察，形成统一且深刻的观点。
  agent: AI_export
  context:
  - Integrative_researcher_summary_answer_task

Microbiology_export_reanswer_task:
  description: >
    运用你在微生物学领域的深厚专业知识，对以下问题给出全面且有理有据的回答：{query}。
    与其简单地对比不同领域的方法或表面融合观点，不如以更深层次的一体化思路展开作答。
    请将微生物学的核心洞察与跨学科专家讨论中提炼出的相关知识无缝整合，用以揭示新的解释视角、解决不确定性，或增强阐述的深度。
  expected_output: >
    一份简洁、逻辑严谨、专业性强的回答（最好不超过500字），既体现出微生物学领域的专家水准，
    又巧妙融合其他领域的上下文洞察，形成统一且深刻的观点。
  agent: Microbiology_export
  context:
  - Integrative_researcher_summary_answer_task