radiological_professor_answer_task:
  description: >
    运用你在本领域的专业知识，对以下问题提供全面的回答：{query}
  expected_output: >
    一份简洁、逻辑清晰、具有专业水准的回答，不超过500字。
  agent: radiological_professor
  async_execution: True

immunology_professor_answer_task:
  description: >
    运用你在本领域的专业知识，对以下问题提供全面的回答：{query}
  expected_output: >
    一份简洁、逻辑清晰、具有专业水准的回答，不超过500字。
  agent: immunology_professor
  async_execution: True

genomics_professor_answer_task:
  description: >
    运用你在本领域的专业知识，对以下问题提供全面的回答：{query}
  expected_output: >
    一份简洁、逻辑清晰、具有专业水准的回答，不超过500字。
  agent: genomics_professor
  async_execution: True

biomedical_informatics_professor_answer_task:
  description: >
    运用你在本领域的专业知识，对以下问题提供全面的回答：{query}
  expected_output: >
    一份简洁、逻辑清晰、具有专业水准的回答，不超过500字。
  agent: biomedical_informatics_professor
  async_execution: True

regenerative_medicine_professor_answer_task:
  description: >
    运用你在本领域的专业知识，对以下问题提供全面的回答：{query}
  expected_output: >
    一份简洁、逻辑清晰、具有专业水准的回答，不超过500字。
  agent: regenerative_medicine_professor
  async_execution: True

clinical_medicine_professor_answer_task:
  description: >
    运用你在本领域的专业知识，对以下问题提供全面的回答：{query}
  expected_output: >
    一份简洁、逻辑清晰、具有专业水准的回答，不超过500字。
  agent: clinical_medicine_professor
  async_execution: True

drug_discovery_professor_answer_task:
  description: >
    运用你在本领域的专业知识，对以下问题提供全面的回答：{query}
  expected_output: >
    一份简洁、逻辑清晰、具有专业水准的回答，不超过500字。
  agent: drug_discovery_professor
  async_execution: True

integrative_researcher_summary_answer_task:
  description: >
    综合来自不同领域专家的回答结果，针对问题：{query}，形成一份整合性的结论报告，反映其多元洞察与观点。
  expected_output: >
    一份全面、连贯的总结报告，将多个领域的专家见解加以整合，形成统一结论，字数不超过800字。
  agent: integrative_researcher
  context:
  - radiological_professor_answer_task
  - immunology_professor_answer_task
  - genomics_professor_answer_task
  - biomedical_informatics_professor_answer_task
  - regenerative_medicine_professor_answer_task
  - clinical_medicine_professor_answer_task
  - drug_discovery_professor_answer_task

medical_ethics_professor_check_answer_task:
  description: >
    审查以下问题的答案：{query}，确保其符合医学伦理标准。如发现回答中存在潜在医学伦理风险，请在相关部分添加“[Ethics Alert]”警示。
  expected_output: >
    对所提供答案的详细审查，指出任何伦理隐患。如回答在伦理上无风险，请明确确认其安全；如发现风险，请在对应部分添加“[Ethics Alert]”标记。
  agent: medical_ethics_professor
  context:
  - integrative_researcher_summary_answer_task